
language: c++
sudo: true

script:
 - mkdir build && cd build
 - cmake ../tmxlite
 - make

matrix:
 include:

    - os: linux
      compiler: gcc

    - os: linux
      compiler: clang

    - os: osx
      osx_image: xcode6.4

    - os: osx
      osx_image: xcode7.3

    - os: osx
      osx_image: xcode8.3

    - os: osx
      osx_image: xcode9